using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Teknik.Helpers
{
    public static class Constants
    {
        public const string SERVERUSER = "Server Admin";
        // Paste Constants
        public static Dictionary<string, string> HIGHLIGHTFORMATS = new Dictionary<string, string>()
        {
            { "1C", "1c" },
            { "Access logs", "accesslog" },
            { "ARM assembler", "armasm" },
            { "AVR assembler", "avrasm" },
            { "ActionScript", "actionscript" },
            { "Apache", "apache" },
            { "AppleScript", "applescript" },
            { "AsciiDoc", "asciidoc" },
            { "AspectJ", "aspectj" },
            { "AutoHotkey", "autohotkey" },
            { "AutoIt", "autoit" },
            { "Axapta", "axapta" },
            { "Bash", "bash" },
            { "Basic", "basic" },
            { "Brainfuck", "brainfuck" },
            { "C#", "cs" },
            { "C++", "cpp" },
            { "C/AL", "cal" },
            { "Cache Object Script", "cos" },
            { "CMake", "cmake" },
            { "CSS", "css" },
            { "Cap’n Proto", "capnproto" },
            { "Clojure", "clojure" },
            { "CoffeeScript", "coffeescript" },
            { "Crmsh", "crmsh" },
            { "Crystal", "crystal" },
            { "D", "d" },
            { "DNS Zone file", "dns" },
            { "DOS", "dos" },
            { "Dart", "dart" },
            { "Delphi", "delphi" },
            { "Diff", "diff" },
            { "Django", "django" },
            { "Dockerfile", "dockerfile" },
            { "DTS (Device Tree)", "dts" },
            { "Dust", "dust" },
            { "Elixir", "elixir" },
            { "Elm", "elm" },
            { "Erlang", "erlang" },
            { "F#", "fsharp" },
            { "FIX", "fix" },
            { "Fortran", "fortran" },
            { "G-Code", "gcode" },
            { "Gams", "gams" },
            { "GAUSS", "gauss" },
            { "Gherkin", "gherkin" },
            { "Go", "go" },
            { "Golo", "golo" },
            { "Gradle", "gradle" },
            { "Groovy", "groovy" },
            { "HTML, XML", "xml" },
            { "HTTP", "http" },
            { "Haml", "haml" },
            { "Handlebars", "handlebars" },
            { "Haskell", "haskell" },
            { "Haxe", "haxe" },
            { "Ini", "ini" },
            { "Inform7", "inform7" },
            { "IRPF90", "irpf90" },
            { "JSON", "json" },
            { "Java", "java" },
            { "JavaScript", "javascript" },
            { "Lasso", "lasso" },
            { "Less", "less" },
            { "Lisp", "lisp" },
            { "LiveCode Server", "livecodeserver" },
            { "LiveScript", "livescript" },
            { "Lua", "lua" },
            { "Makefile", "makefile" },
            { "Markdown", "markdown" },
            { "Mathematica", "mathematica" },
            { "Matlab", "matlab" },
            { "Maya Embedded Language", "mel" },
            { "Mercury", "mercury" },
            { "Mizar", "mizar" },
            { "Mojolicious", "mojolicious" },
            { "Monkey", "monkey" },
            { "NSIS", "nsis" },
            { "Nginx", "nginx" },
            { "Nimrod", "nimrod" },
            { "Nix", "nix" },
            { "OCaml", "ocaml" },
            { "Objective C", "objectivec" },
            { "OpenGL Shading Language", "glsl" },
            { "OpenSCAD", "openscad" },
            { "Oracle Rules Language", "ruleslanguage" },
            { "Oxygene", "oxygene" },
            { "PF", "pf" },
            { "PHP", "php" },
            { "Parser3", "parser3" },
            { "Perl", "perl" },
            { "PowerShell", "powershell" },
            { "Processing", "processing" },
            { "Prolog", "prolog" },
            { "Protocol Buffers", "protobuf" },
            { "Puppet", "puppet" },
            { "Python", "python" },
            { "Python profiler results", "profile" },
            { "Q", "k" },
            { "QML", "qml" },
            { "R", "r" },
            { "RenderMan RIB", "rib" },
            { "RenderMan RSL", "rsl" },
            { "Roboconf", "graph" },
            { "Ruby", "ruby" },
            { "Rust", "rust" },
            { "SCSS", "scss" },
            { "SQL", "sql" },
            { "STEP Part 21", "p21" },
            { "Scala", "scala" },
            { "Scheme", "scheme" },
            { "Scilab", "scilab" },
            { "Smali", "smali" },
            { "Smalltalk", "smalltalk" },
            { "Stan", "stan" },
            { "Stata", "stata" },
            { "Stylus", "stylus" },
            { "Swift", "swift" },
            { "Tcl", "tcl" },
            { "TeX", "tex" },
            { "Thrift", "thrift" },
            { "TP", "tp" },
            { "Twig", "twig" },
            { "TypeScript", "typescript" },
            { "VB.Net", "vbnet" },
            { "VBScript", "vbscript" },
            { "VHDL", "vhdl" },
            { "Vala", "vala" },
            { "Verilog", "verilog" },
            { "Vim Script", "vim" },
            { "x86 Assembly", "x86asm" },
            { "XL", "xl" },
            { "XQuery", "xpath" },
            { "Zephir", "zephir" }
        };
    }
}
