// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teknik.Data;

namespace Teknik.Data.Migrations
{
    [DbContext(typeof(TeknikEntities))]
    [Migration("20211113052031_RenameUploadSettings")]
    partial class RenameUploadSettings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Teknik.Areas.Billing.Models.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("CaseSensitive", true);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Teknik.Areas.Blog.Models.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BlogId");

                    b.HasIndex("UserId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("Teknik.Areas.Blog.Models.BlogPost", b =>
                {
                    b.Property<int>("BlogPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Article")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEdited")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<bool>("System")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BlogPostId");

                    b.HasIndex("BlogId");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("Teknik.Areas.Blog.Models.BlogPostComment", b =>
                {
                    b.Property<int>("BlogPostCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Article")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BlogPostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEdited")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BlogPostCommentId");

                    b.HasIndex("BlogPostId");

                    b.HasIndex("UserId");

                    b.ToTable("BlogPostComments");
                });

            modelBuilder.Entity("Teknik.Areas.Blog.Models.BlogPostTag", b =>
                {
                    b.Property<int>("BlogPostTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlogPostId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BlogPostTagId");

                    b.HasIndex("BlogPostId");

                    b.ToTable("BlogPostTags");
                });

            modelBuilder.Entity("Teknik.Areas.Contact.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("Teknik.Areas.Paste.Models.Paste", b =>
                {
                    b.Property<int>("PasteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlockSize")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEdited")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteKey")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("CaseSensitive", true);

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("CaseSensitive", true);

                    b.Property<string>("HashedPassword")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("CaseSensitive", true);

                    b.Property<string>("IV")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("CaseSensitive", true);

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("CaseSensitive", true);

                    b.Property<int>("KeySize")
                        .HasColumnType("int");

                    b.Property<int>("MaxViews")
                        .HasColumnType("int");

                    b.Property<string>("Syntax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("CaseSensitive", true);

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("PasteId");

                    b.HasIndex("UserId");

                    b.ToTable("Pastes");
                });

            modelBuilder.Entity("Teknik.Areas.Podcast.Models.Podcast", b =>
                {
                    b.Property<int>("PodcastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateEdited")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Episode")
                        .HasColumnType("int");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PodcastId");

                    b.ToTable("Podcasts");
                });

            modelBuilder.Entity("Teknik.Areas.Podcast.Models.PodcastComment", b =>
                {
                    b.Property<int>("PodcastCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Article")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEdited")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<int>("PodcastId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PodcastCommentId");

                    b.HasIndex("PodcastId");

                    b.HasIndex("UserId");

                    b.ToTable("PodcastComments");
                });

            modelBuilder.Entity("Teknik.Areas.Podcast.Models.PodcastFile", b =>
                {
                    b.Property<int>("PodcastFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ContentLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PodcastId")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("PodcastFileId");

                    b.HasIndex("PodcastId");

                    b.ToTable("PodcastFiles");
                });

            modelBuilder.Entity("Teknik.Areas.Podcast.Models.PodcastTag", b =>
                {
                    b.Property<int>("PodcastTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PodcastId")
                        .HasColumnType("int");

                    b.HasKey("PodcastTagId");

                    b.HasIndex("PodcastId");

                    b.ToTable("PodcastTags");
                });

            modelBuilder.Entity("Teknik.Areas.Shortener.Models.ShortenedUrl", b =>
                {
                    b.Property<int>("ShortenedUrlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginalUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("CaseSensitive", true);

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("ShortenedUrlId");

                    b.HasIndex("UserId");

                    b.ToTable("ShortenedUrls");
                });

            modelBuilder.Entity("Teknik.Areas.Stats.Models.Takedown", b =>
                {
                    b.Property<int>("TakedownId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionTaken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateActionTaken")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requester")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequesterContact")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TakedownId");

                    b.ToTable("Takedowns");
                });

            modelBuilder.Entity("Teknik.Areas.Stats.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(19,5)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateSent")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Teknik.Areas.Upload.Models.Upload", b =>
                {
                    b.Property<int>("UploadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlockSize")
                        .HasColumnType("int");

                    b.Property<long>("ContentLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteKey")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("CaseSensitive", true);

                    b.Property<int>("Downloads")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("CaseSensitive", true);

                    b.Property<string>("IV")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("CaseSensitive", true);

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("CaseSensitive", true);

                    b.Property<int>("KeySize")
                        .HasColumnType("int");

                    b.Property<int>("MaxDownloads")
                        .HasColumnType("int");

                    b.Property<int?>("Takedown_TakedownId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("CaseSensitive", true);

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UploadId");

                    b.HasIndex("Takedown_TakedownId");

                    b.HasIndex("UserId");

                    b.ToTable("Uploads");
                });

            modelBuilder.Entity("Teknik.Areas.Users.Models.Feature", b =>
                {
                    b.Property<string>("FeatureId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeatureId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("Teknik.Areas.Users.Models.InviteCode", b =>
                {
                    b.Property<int>("InviteCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("ClaimedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("CaseSensitive", true);

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("InviteCodeId");

                    b.HasIndex("ClaimedUserId")
                        .IsUnique()
                        .HasFilter("[ClaimedUserId] IS NOT NULL");

                    b.HasIndex("OwnerId");

                    b.ToTable("InviteCodes");
                });

            modelBuilder.Entity("Teknik.Areas.Users.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Teknik.Areas.Users.Models.UserFeature", b =>
                {
                    b.Property<int>("UserFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FeatureId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserFeatureId");

                    b.HasIndex("FeatureId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFeatures");
                });

            modelBuilder.Entity("Teknik.Areas.Vault.Models.Vault", b =>
                {
                    b.Property<int>("VaultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEdited")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("VaultId");

                    b.HasIndex("UserId");

                    b.ToTable("Vaults");
                });

            modelBuilder.Entity("Teknik.Areas.Vault.Models.VaultItem", b =>
                {
                    b.Property<int>("VaultItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VaultId")
                        .HasColumnType("int");

                    b.HasKey("VaultItemId");

                    b.HasIndex("VaultId");

                    b.ToTable("VaultItems");

                    b.HasDiscriminator<string>("Discriminator").HasValue("VaultItem");
                });

            modelBuilder.Entity("Teknik.Areas.Vault.Models.PasteVaultItem", b =>
                {
                    b.HasBaseType("Teknik.Areas.Vault.Models.VaultItem");

                    b.Property<int>("PasteId")
                        .HasColumnType("int");

                    b.HasIndex("PasteId");

                    b.HasDiscriminator().HasValue("PasteVaultItem");
                });

            modelBuilder.Entity("Teknik.Areas.Vault.Models.UploadVaultItem", b =>
                {
                    b.HasBaseType("Teknik.Areas.Vault.Models.VaultItem");

                    b.Property<int>("UploadId")
                        .HasColumnType("int");

                    b.HasIndex("UploadId");

                    b.HasDiscriminator().HasValue("UploadVaultItem");
                });

            modelBuilder.Entity("Teknik.Areas.Billing.Models.Customer", b =>
                {
                    b.HasOne("Teknik.Areas.Users.Models.User", "User")
                        .WithOne("BillingCustomer")
                        .HasForeignKey("Teknik.Areas.Billing.Models.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Teknik.Areas.Blog.Models.Blog", b =>
                {
                    b.HasOne("Teknik.Areas.Users.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Teknik.Areas.Blog.Models.BlogPost", b =>
                {
                    b.HasOne("Teknik.Areas.Blog.Models.Blog", "Blog")
                        .WithMany("BlogPosts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("Teknik.Areas.Blog.Models.BlogPostComment", b =>
                {
                    b.HasOne("Teknik.Areas.Blog.Models.BlogPost", "BlogPost")
                        .WithMany("Comments")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teknik.Areas.Users.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("BlogPost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Teknik.Areas.Blog.Models.BlogPostTag", b =>
                {
                    b.HasOne("Teknik.Areas.Blog.Models.BlogPost", "BlogPost")
                        .WithMany("Tags")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("Teknik.Areas.Paste.Models.Paste", b =>
                {
                    b.HasOne("Teknik.Areas.Users.Models.User", "User")
                        .WithMany("Pastes")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Teknik.Areas.Podcast.Models.PodcastComment", b =>
                {
                    b.HasOne("Teknik.Areas.Podcast.Models.Podcast", "Podcast")
                        .WithMany("Comments")
                        .HasForeignKey("PodcastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teknik.Areas.Users.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Podcast");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Teknik.Areas.Podcast.Models.PodcastFile", b =>
                {
                    b.HasOne("Teknik.Areas.Podcast.Models.Podcast", "Podcast")
                        .WithMany("Files")
                        .HasForeignKey("PodcastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Podcast");
                });

            modelBuilder.Entity("Teknik.Areas.Podcast.Models.PodcastTag", b =>
                {
                    b.HasOne("Teknik.Areas.Podcast.Models.Podcast", "Podcast")
                        .WithMany("Tags")
                        .HasForeignKey("PodcastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Podcast");
                });

            modelBuilder.Entity("Teknik.Areas.Shortener.Models.ShortenedUrl", b =>
                {
                    b.HasOne("Teknik.Areas.Users.Models.User", "User")
                        .WithMany("ShortenedUrls")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Teknik.Areas.Upload.Models.Upload", b =>
                {
                    b.HasOne("Teknik.Areas.Stats.Models.Takedown", null)
                        .WithMany("Attachments")
                        .HasForeignKey("Takedown_TakedownId");

                    b.HasOne("Teknik.Areas.Users.Models.User", "User")
                        .WithMany("Uploads")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Teknik.Areas.Users.Models.InviteCode", b =>
                {
                    b.HasOne("Teknik.Areas.Users.Models.User", "ClaimedUser")
                        .WithOne("ClaimedInviteCode")
                        .HasForeignKey("Teknik.Areas.Users.Models.InviteCode", "ClaimedUserId");

                    b.HasOne("Teknik.Areas.Users.Models.User", "Owner")
                        .WithMany("OwnedInviteCodes")
                        .HasForeignKey("OwnerId");

                    b.Navigation("ClaimedUser");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Teknik.Areas.Users.Models.User", b =>
                {
                    b.OwnsOne("Teknik.Areas.Users.Models.BlogSettings", "BlogSettings", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Description");

                            b1.Property<string>("Title")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Title");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Teknik.Areas.Users.Models.UploadSettings", "UploadSettings", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<bool>("Encrypt")
                                .HasColumnType("bit")
                                .HasColumnName("Encrypt");

                            b1.Property<int>("ExpirationLength")
                                .HasColumnType("int")
                                .HasColumnName("ExpirationLength");

                            b1.Property<int>("ExpirationUnit")
                                .HasColumnType("int")
                                .HasColumnName("ExpirationUnit");

                            b1.Property<long?>("MaxUploadFileSize")
                                .HasColumnType("bigint")
                                .HasColumnName("MaxUploadFileSize");

                            b1.Property<long?>("MaxUploadStorage")
                                .HasColumnType("bigint")
                                .HasColumnName("MaxUploadStorage");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Teknik.Areas.Users.Models.UserSettings", "UserSettings", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("About")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("About");

                            b1.Property<string>("Quote")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Quote");

                            b1.Property<string>("Website")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Website");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("BlogSettings");

                    b.Navigation("UploadSettings");

                    b.Navigation("UserSettings");
                });

            modelBuilder.Entity("Teknik.Areas.Users.Models.UserFeature", b =>
                {
                    b.HasOne("Teknik.Areas.Users.Models.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId");

                    b.HasOne("Teknik.Areas.Users.Models.User", "User")
                        .WithMany("Features")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Teknik.Areas.Vault.Models.Vault", b =>
                {
                    b.HasOne("Teknik.Areas.Users.Models.User", "User")
                        .WithMany("Vaults")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Teknik.Areas.Vault.Models.VaultItem", b =>
                {
                    b.HasOne("Teknik.Areas.Vault.Models.Vault", "Vault")
                        .WithMany("VaultItems")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("Teknik.Areas.Vault.Models.PasteVaultItem", b =>
                {
                    b.HasOne("Teknik.Areas.Paste.Models.Paste", "Paste")
                        .WithMany("PasteVaultItems")
                        .HasForeignKey("PasteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paste");
                });

            modelBuilder.Entity("Teknik.Areas.Vault.Models.UploadVaultItem", b =>
                {
                    b.HasOne("Teknik.Areas.Upload.Models.Upload", "Upload")
                        .WithMany("UploadVaultItems")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("Teknik.Areas.Blog.Models.Blog", b =>
                {
                    b.Navigation("BlogPosts");
                });

            modelBuilder.Entity("Teknik.Areas.Blog.Models.BlogPost", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Teknik.Areas.Paste.Models.Paste", b =>
                {
                    b.Navigation("PasteVaultItems");
                });

            modelBuilder.Entity("Teknik.Areas.Podcast.Models.Podcast", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Files");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Teknik.Areas.Stats.Models.Takedown", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Teknik.Areas.Upload.Models.Upload", b =>
                {
                    b.Navigation("UploadVaultItems");
                });

            modelBuilder.Entity("Teknik.Areas.Users.Models.User", b =>
                {
                    b.Navigation("BillingCustomer");

                    b.Navigation("ClaimedInviteCode");

                    b.Navigation("Features");

                    b.Navigation("OwnedInviteCodes");

                    b.Navigation("Pastes");

                    b.Navigation("ShortenedUrls");

                    b.Navigation("Uploads");

                    b.Navigation("Vaults");
                });

            modelBuilder.Entity("Teknik.Areas.Vault.Models.Vault", b =>
                {
                    b.Navigation("VaultItems");
                });
#pragma warning restore 612, 618
        }
    }
}
