-- Uploads
ALTER TABLE Uploads 
	ALTER COLUMN [Url] NVARCHAR(MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
ALTER TABLE Uploads 
	ALTER COLUMN [FileName] NVARCHAR(MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
ALTER TABLE Uploads 
	ALTER COLUMN [Key] NVARCHAR(MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
ALTER TABLE Uploads 
	ALTER COLUMN [IV] NVARCHAR(MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
ALTER TABLE Uploads 
	ALTER COLUMN [DeleteKey] NVARCHAR(MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL

-- Users
ALTER TABLE Users 
	ALTER COLUMN [HashedPassword] NVARCHAR(MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL

-- Pastes
ALTER TABLE Pastes 
	ALTER COLUMN [Url] NVARCHAR(MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
ALTER TABLE Pastes 
	ALTER COLUMN [HashedPassword] NVARCHAR(MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
ALTER TABLE Pastes 
	ALTER COLUMN [Key] NVARCHAR(MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
ALTER TABLE Pastes 
	ALTER COLUMN [IV] NVARCHAR(MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL

-- Shortened Urls
ALTER TABLE ShortenedUrls 
	ALTER COLUMN [ShortUrl] NVARCHAR(MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL